name: Python CI Pipeline

on: [push]

jobs:
  test-logic:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install Dependencies
        run: |
          # Создадим пустой файл, чтобы pip не ругался, если его нет
          touch requirements.txt
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          echo "Запуск тестов..."
          # Просто выведем версию, так как тестов пока нет
          pytest --version || echo "Pytest пока не установлен, но пайплайн работает!"
      - name: Send Telegram notification
        # Этот шаг сработает только если ТЕСТЫ упали
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Пайплайн упал!
            Репозиторий: ${{ github.repository }}
            Автор: ${{ github.actor }}
            Посмотреть ошибку: https://github.com/${{ github.repository  }}/actions/runs/${{ github.run_id }}
          
        
